name: Felicity
career_focus:
  - "UX design"
  - "Service design"
  - "Product strategy"

values:
  - "Social impact"
  - "Wellbeing"
  - "Accessibility"
  - "Positive culture"
  - "inclusion"

exclude:
  - "commission-only"
  - "door-to-door sales"
  - "intern"

results_per_day: 10

  
filters:
  remote_only: false  # allow hybrid/ on-site as well
